version: "3.9"

services:

  react:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile.dev"
    environment:
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - "./frontend/src:/frontend/src"
      - "./frontend/public:/frontend/public"
    ports:
      - "80:3000"

  flask:
    build:
      context: "./backend"
      dockerfile: "Dockerfile.dev"
    volumes:
      - "./backend/api:/backend/api"
    ports:
      - "5000:5000"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: none

  # nginx
