FROM python:3

WORKDIR /backend

RUN apt-get update -y
RUN python -m pip install --upgrade pip

COPY requirements.txt .

RUN pip3 install -r requirements.txt

ENV FLASK_APP=api
ENV FLASK_ENV=development

EXPOSE 5000
ENTRYPOINT flask run --host=0.0.0.0 --port=5000